### PR TITLE
Minor memory leak; unused variable

### PR DESCRIPTION
**Pull request by schuellerf**

### CODE REVIEW

**Comment by ochosi** [comment]
Normally the maintainers put their names in the about dialogue - so if you wanna do that that's great ;)
Contributors I'd put in the (less prominent) AUTHORS file, but ultimately this is a matter of taste/convention.

**Comment by schuellerf** [comment]
Being maintainer without a clue about GTK seems ridiculous :) I'll revert the commit...

**Comment by ochosi** [comment]
So far nothing here has been pushed to git.xfce.org, so there's enough time for catching up (plus Gtk is only a toolkit...) ;)

**Comment by ochosi** [comment]
Decided to cherry-pick the commits here and push them straight to my gtk3 branch (and avoid the two superfluous commits to the about dialog)

**Pull request closed without merging**
